# Form implementation generated from reading ui file 'c:\Users\ciren\Desktop\二次开发\TCP-IP-Python-V4_HMI\testHMI.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1413, 666)
        MainWindow.setStyleSheet("")
        MainWindow.setIconSize(QtCore.QSize(28, 18))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.connect = QtWidgets.QPushButton(parent=self.centralwidget)
        self.connect.setGeometry(QtCore.QRect(320, 110, 100, 40))
        self.connect.setMinimumSize(QtCore.QSize(0, 0))
        self.connect.setStyleSheet("QPushButton {\n"
"    background-color: #228B22;  /* 深绿色背景色 */\n"
"    color: white;  /* 文字颜色 */\n"
"    border-radius: 10px;  /* 圆角 */\n"
"    font-size: 16px;  /* 字体大小 */\n"
"    padding: 8px 16px;  /* 内边距 */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #1E7B1E; /* 悬停时颜色，略深 */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #166D16; /* 按下时颜色，更深 */\n"
"}\n"
"")
        self.connect.setObjectName("connect")
        self.get_IP = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.get_IP.setGeometry(QtCore.QRect(160, 110, 131, 43))
        self.get_IP.setMinimumSize(QtCore.QSize(0, 43))
        self.get_IP.setStyleSheet("QLineEdit {\n"
"    background-color: #ecf0f1;  /* 浅灰色背景 */\n"
"    color: #2c3e50;  /* 文字颜色 */\n"
"    border: 2px solid #bdc3c7;  /* 默认边框 */\n"
"    border-radius: 10px;  /* 圆角 */\n"
"    font-size: 18px;  /* 字体大小，增加到18px */\n"
"    padding: 12px 16px;  /* 增大内边距，使文字更居中 */\n"
"    min-height: 15px;  /* 设置最小高度，保证输入框足够大 */ \n"
"    selection-background-color: #3498db;  /* 选中文字背景色 */\n"
"    selection-color: white;  /* 选中文字颜色 */\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid #95a5a6;  /* 悬停时边框颜色 */\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid #3498db;  /* 聚焦时边框变蓝 */\n"
"    background-color: white;  /* 聚焦时背景变白 */\n"
"}\n"
"QLineEdit:disabled {\n"
"    background-color: #bdc3c7;  /* 禁用时背景变灰 */\n"
"    color: #7f8c8d;  /* 禁用时字体颜色变暗 */\n"
"}\n"
"")
        self.get_IP.setObjectName("get_IP")
        self.IP_Adress = QtWidgets.QLabel(parent=self.centralwidget)
        self.IP_Adress.setGeometry(QtCore.QRect(10, 120, 131, 31))
        self.IP_Adress.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.IP_Adress.setFont(font)
        self.IP_Adress.setObjectName("IP_Adress")
        self.Dashboard_Port = QtWidgets.QLabel(parent=self.centralwidget)
        self.Dashboard_Port.setGeometry(QtCore.QRect(10, 170, 151, 31))
        self.Dashboard_Port.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Dashboard_Port.setFont(font)
        self.Dashboard_Port.setObjectName("Dashboard_Port")
        self.get_Dashbord_P = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.get_Dashbord_P.setGeometry(QtCore.QRect(160, 160, 131, 43))
        self.get_Dashbord_P.setMinimumSize(QtCore.QSize(0, 43))
        self.get_Dashbord_P.setStyleSheet("QLineEdit {\n"
"    background-color: #ecf0f1;  /* 浅灰色背景 */\n"
"    color: #2c3e50;  /* 文字颜色 */\n"
"    border: 2px solid #bdc3c7;  /* 默认边框 */\n"
"    border-radius: 10px;  /* 圆角 */\n"
"    font-size: 18px;  /* 字体大小，增加到18px */\n"
"    padding: 12px 16px;  /* 增大内边距，使文字更居中 */\n"
"    min-height: 15px;  /* 设置最小高度，保证输入框足够大 */ \n"
"    selection-background-color: #3498db;  /* 选中文字背景色 */\n"
"    selection-color: white;  /* 选中文字颜色 */\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid #95a5a6;  /* 悬停时边框颜色 */\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid #3498db;  /* 聚焦时边框变蓝 */\n"
"    background-color: white;  /* 聚焦时背景变白 */\n"
"}\n"
"QLineEdit:disabled {\n"
"    background-color: #bdc3c7;  /* 禁用时背景变灰 */\n"
"    color: #7f8c8d;  /* 禁用时字体颜色变暗 */\n"
"}\n"
"")
        self.get_Dashbord_P.setObjectName("get_Dashbord_P")
        self.get_Feedback_P = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.get_Feedback_P.setGeometry(QtCore.QRect(159, 210, 131, 43))
        self.get_Feedback_P.setMinimumSize(QtCore.QSize(0, 43))
        self.get_Feedback_P.setStyleSheet("QLineEdit {\n"
"    background-color: #ecf0f1;  /* 浅灰色背景 */\n"
"    color: #2c3e50;  /* 文字颜色 */\n"
"    border: 2px solid #bdc3c7;  /* 默认边框 */\n"
"    border-radius: 10px;  /* 圆角 */\n"
"    font-size: 18px;  /* 字体大小，增加到18px */\n"
"    padding: 12px 16px;  /* 增大内边距，使文字更居中 */\n"
"    min-height: 15px;  /* 设置最小高度，保证输入框足够大 */ \n"
"    selection-background-color: #3498db;  /* 选中文字背景色 */\n"
"    selection-color: white;  /* 选中文字颜色 */\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid #95a5a6;  /* 悬停时边框颜色 */\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid #3498db;  /* 聚焦时边框变蓝 */\n"
"    background-color: white;  /* 聚焦时背景变白 */\n"
"}\n"
"QLineEdit:disabled {\n"
"    background-color: #bdc3c7;  /* 禁用时背景变灰 */\n"
"    color: #7f8c8d;  /* 禁用时字体颜色变暗 */\n"
"}\n"
"")
        self.get_Feedback_P.setObjectName("get_Feedback_P")
        self.Feedback_Port = QtWidgets.QLabel(parent=self.centralwidget)
        self.Feedback_Port.setGeometry(QtCore.QRect(10, 210, 131, 41))
        self.Feedback_Port.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Feedback_Port.setFont(font)
        self.Feedback_Port.setObjectName("Feedback_Port")
        self.Enable = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Enable.setGeometry(QtCore.QRect(320, 210, 100, 40))
        self.Enable.setMinimumSize(QtCore.QSize(0, 0))
        self.Enable.setMaximumSize(QtCore.QSize(190, 70))
        self.Enable.setStyleSheet("QPushButton {\n"
"    background-color: #228B22;  /* 深绿色背景色 */\n"
"    color: white;  /* 文字颜色 */\n"
"    border-radius: 10px;  /* 圆角 */\n"
"    font-size: 16px;  /* 字体大小 */\n"
"    padding: 8px 16px;  /* 内边距 */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #1E7B1E; /* 悬停时颜色，略深 */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #166D16; /* 按下时颜色，更深 */\n"
"}\n"
"")
        self.Enable.setObjectName("Enable")
        self.get_J1 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.get_J1.setGeometry(QtCore.QRect(150, 270, 120, 43))
        self.get_J1.setMinimumSize(QtCore.QSize(0, 43))
        self.get_J1.setStyleSheet("QLineEdit {\n"
"    background-color: #ecf0f1;  /* 浅灰色背景 */\n"
"    color: #2c3e50;  /* 文字颜色 */\n"
"    border: 2px solid #bdc3c7;  /* 默认边框 */\n"
"    border-radius: 10px;  /* 圆角 */\n"
"    font-size: 18px;  /* 字体大小，增加到18px */\n"
"    padding: 12px 16px;  /* 增大内边距，使文字更居中 */\n"
"    min-height: 15px;  /* 设置最小高度，保证输入框足够大 */ \n"
"    selection-background-color: #3498db;  /* 选中文字背景色 */\n"
"    selection-color: white;  /* 选中文字颜色 */\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid #95a5a6;  /* 悬停时边框颜色 */\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid #3498db;  /* 聚焦时边框变蓝 */\n"
"    background-color: white;  /* 聚焦时背景变白 */\n"
"}\n"
"QLineEdit:disabled {\n"
"    background-color: #bdc3c7;  /* 禁用时背景变灰 */\n"
"    color: #7f8c8d;  /* 禁用时字体颜色变暗 */\n"
"}\n"
"")
        self.get_J1.setObjectName("get_J1")
        self.J1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.J1.setGeometry(QtCore.QRect(120, 260, 21, 40))
        self.J1.setMinimumSize(QtCore.QSize(0, 0))
        self.J1.setMaximumSize(QtCore.QSize(16777215, 1111))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.J1.setFont(font)
        self.J1.setStyleSheet("")
        self.J1.setObjectName("J1")
        self.J2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.J2.setGeometry(QtCore.QRect(120, 310, 100, 40))
        self.J2.setMinimumSize(QtCore.QSize(0, 0))
        self.J2.setMaximumSize(QtCore.QSize(16777215, 1111))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.J2.setFont(font)
        self.J2.setStyleSheet("")
        self.J2.setObjectName("J2")
        self.get_J2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.get_J2.setGeometry(QtCore.QRect(150, 320, 120, 43))
        self.get_J2.setMinimumSize(QtCore.QSize(0, 43))
        self.get_J2.setStyleSheet("QLineEdit {\n"
"    background-color: #ecf0f1;  /* 浅灰色背景 */\n"
"    color: #2c3e50;  /* 文字颜色 */\n"
"    border: 2px solid #bdc3c7;  /* 默认边框 */\n"
"    border-radius: 10px;  /* 圆角 */\n"
"    font-size: 18px;  /* 字体大小，增加到18px */\n"
"    padding: 12px 16px;  /* 增大内边距，使文字更居中 */\n"
"    min-height: 15px;  /* 设置最小高度，保证输入框足够大 */ \n"
"    selection-background-color: #3498db;  /* 选中文字背景色 */\n"
"    selection-color: white;  /* 选中文字颜色 */\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid #95a5a6;  /* 悬停时边框颜色 */\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid #3498db;  /* 聚焦时边框变蓝 */\n"
"    background-color: white;  /* 聚焦时背景变白 */\n"
"}\n"
"QLineEdit:disabled {\n"
"    background-color: #bdc3c7;  /* 禁用时背景变灰 */\n"
"    color: #7f8c8d;  /* 禁用时字体颜色变暗 */\n"
"}\n"
"")
        self.get_J2.setObjectName("get_J2")
        self.J3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.J3.setGeometry(QtCore.QRect(120, 360, 100, 40))
        self.J3.setMinimumSize(QtCore.QSize(0, 0))
        self.J3.setMaximumSize(QtCore.QSize(16777215, 1111))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.J3.setFont(font)
        self.J3.setStyleSheet("")
        self.J3.setObjectName("J3")
        self.get_J3 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.get_J3.setGeometry(QtCore.QRect(150, 370, 120, 43))
        self.get_J3.setMinimumSize(QtCore.QSize(0, 43))
        self.get_J3.setStyleSheet("QLineEdit {\n"
"    background-color: #ecf0f1;  /* 浅灰色背景 */\n"
"    color: #2c3e50;  /* 文字颜色 */\n"
"    border: 2px solid #bdc3c7;  /* 默认边框 */\n"
"    border-radius: 10px;  /* 圆角 */\n"
"    font-size: 18px;  /* 字体大小，增加到18px */\n"
"    padding: 12px 16px;  /* 增大内边距，使文字更居中 */\n"
"    min-height: 15px;  /* 设置最小高度，保证输入框足够大 */ \n"
"    selection-background-color: #3498db;  /* 选中文字背景色 */\n"
"    selection-color: white;  /* 选中文字颜色 */\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid #95a5a6;  /* 悬停时边框颜色 */\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid #3498db;  /* 聚焦时边框变蓝 */\n"
"    background-color: white;  /* 聚焦时背景变白 */\n"
"}\n"
"QLineEdit:disabled {\n"
"    background-color: #bdc3c7;  /* 禁用时背景变灰 */\n"
"    color: #7f8c8d;  /* 禁用时字体颜色变暗 */\n"
"}\n"
"")
        self.get_J3.setObjectName("get_J3")
        self.J4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.J4.setGeometry(QtCore.QRect(120, 410, 31, 40))
        self.J4.setMinimumSize(QtCore.QSize(0, 0))
        self.J4.setMaximumSize(QtCore.QSize(16777215, 1111))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.J4.setFont(font)
        self.J4.setStyleSheet("")
        self.J4.setObjectName("J4")
        self.J5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.J5.setGeometry(QtCore.QRect(120, 520, 100, 40))
        self.J5.setMinimumSize(QtCore.QSize(0, 0))
        self.J5.setMaximumSize(QtCore.QSize(16777215, 1111))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.J5.setFont(font)
        self.J5.setStyleSheet("")
        self.J5.setObjectName("J5")
        self.get_J5 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.get_J5.setGeometry(QtCore.QRect(150, 470, 120, 43))
        self.get_J5.setMinimumSize(QtCore.QSize(0, 43))
        self.get_J5.setStyleSheet("QLineEdit {\n"
"    background-color: #ecf0f1;  /* 浅灰色背景 */\n"
"    color: #2c3e50;  /* 文字颜色 */\n"
"    border: 2px solid #bdc3c7;  /* 默认边框 */\n"
"    border-radius: 10px;  /* 圆角 */\n"
"    font-size: 18px;  /* 字体大小，增加到18px */\n"
"    padding: 12px 16px;  /* 增大内边距，使文字更居中 */\n"
"    min-height: 15px;  /* 设置最小高度，保证输入框足够大 */ \n"
"    selection-background-color: #3498db;  /* 选中文字背景色 */\n"
"    selection-color: white;  /* 选中文字颜色 */\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid #95a5a6;  /* 悬停时边框颜色 */\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid #3498db;  /* 聚焦时边框变蓝 */\n"
"    background-color: white;  /* 聚焦时背景变白 */\n"
"}\n"
"QLineEdit:disabled {\n"
"    background-color: #bdc3c7;  /* 禁用时背景变灰 */\n"
"    color: #7f8c8d;  /* 禁用时字体颜色变暗 */\n"
"}\n"
"")
        self.get_J5.setObjectName("get_J5")
        self.get_J6 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.get_J6.setGeometry(QtCore.QRect(150, 520, 120, 43))
        self.get_J6.setMinimumSize(QtCore.QSize(0, 43))
        self.get_J6.setStyleSheet("QLineEdit {\n"
"    background-color: #ecf0f1;  /* 浅灰色背景 */\n"
"    color: #2c3e50;  /* 文字颜色 */\n"
"    border: 2px solid #bdc3c7;  /* 默认边框 */\n"
"    border-radius: 10px;  /* 圆角 */\n"
"    font-size: 18px;  /* 字体大小，增加到18px */\n"
"    padding: 12px 16px;  /* 增大内边距，使文字更居中 */\n"
"    min-height: 15px;  /* 设置最小高度，保证输入框足够大 */ \n"
"    selection-background-color: #3498db;  /* 选中文字背景色 */\n"
"    selection-color: white;  /* 选中文字颜色 */\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid #95a5a6;  /* 悬停时边框颜色 */\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid #3498db;  /* 聚焦时边框变蓝 */\n"
"    background-color: white;  /* 聚焦时背景变白 */\n"
"}\n"
"QLineEdit:disabled {\n"
"    background-color: #bdc3c7;  /* 禁用时背景变灰 */\n"
"    color: #7f8c8d;  /* 禁用时字体颜色变暗 */\n"
"}\n"
"")
        self.get_J6.setObjectName("get_J6")
        self.get_J4 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.get_J4.setGeometry(QtCore.QRect(150, 420, 120, 43))
        self.get_J4.setMinimumSize(QtCore.QSize(0, 43))
        self.get_J4.setStyleSheet("QLineEdit {\n"
"    background-color: #ecf0f1;  /* 浅灰色背景 */\n"
"    color: #2c3e50;  /* 文字颜色 */\n"
"    border: 2px solid #bdc3c7;  /* 默认边框 */\n"
"    border-radius: 10px;  /* 圆角 */\n"
"    font-size: 18px;  /* 字体大小，增加到18px */\n"
"    padding: 12px 16px;  /* 增大内边距，使文字更居中 */\n"
"    min-height: 15px;  /* 设置最小高度，保证输入框足够大 */ \n"
"    selection-background-color: #3498db;  /* 选中文字背景色 */\n"
"    selection-color: white;  /* 选中文字颜色 */\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid #95a5a6;  /* 悬停时边框颜色 */\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid #3498db;  /* 聚焦时边框变蓝 */\n"
"    background-color: white;  /* 聚焦时背景变白 */\n"
"}\n"
"QLineEdit:disabled {\n"
"    background-color: #bdc3c7;  /* 禁用时背景变灰 */\n"
"    color: #7f8c8d;  /* 禁用时字体颜色变暗 */\n"
"}\n"
"")
        self.get_J4.setObjectName("get_J4")
        self.J6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.J6.setGeometry(QtCore.QRect(120, 470, 100, 40))
        self.J6.setMinimumSize(QtCore.QSize(0, 0))
        self.J6.setMaximumSize(QtCore.QSize(16777215, 1111))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.J6.setFont(font)
        self.J6.setStyleSheet("")
        self.J6.setObjectName("J6")
        self.J1P = QtWidgets.QPushButton(parent=self.centralwidget)
        self.J1P.setGeometry(QtCore.QRect(10, 260, 100, 40))
        self.J1P.setMinimumSize(QtCore.QSize(0, 0))
        self.J1P.setMaximumSize(QtCore.QSize(190, 70))
        self.J1P.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.J1P.setStyleSheet("QPushButton {\n"
"    background-color: #3498db;  /* 按钮背景色 */\n"
"    color: white;  /* 文字颜色 */\n"
"    border-radius: 10px;  /* 圆角 */\n"
"    font-size: 16px;  /* 字体大小 */\n"
"    padding: 8px 16px;  /* 内边距 */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #2980b9; /* 悬停颜色 */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #1c6690; /* 按下颜色 */\n"
"}")
        self.J1P.setObjectName("J1P")
        self.J1N = QtWidgets.QPushButton(parent=self.centralwidget)
        self.J1N.setGeometry(QtCore.QRect(290, 260, 100, 40))
        self.J1N.setMinimumSize(QtCore.QSize(0, 0))
        self.J1N.setMaximumSize(QtCore.QSize(190, 70))
        self.J1N.setStyleSheet("QPushButton {\n"
"    background-color: #3498db;  /* 按钮背景色 */\n"
"    color: white;  /* 文字颜色 */\n"
"    border-radius: 10px;  /* 圆角 */\n"
"    font-size: 16px;  /* 字体大小 */\n"
"    padding: 8px 16px;  /* 内边距 */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #2980b9; /* 悬停颜色 */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #1c6690; /* 按下颜色 */\n"
"}")
        self.J1N.setObjectName("J1N")
        self.J2P = QtWidgets.QPushButton(parent=self.centralwidget)
        self.J2P.setGeometry(QtCore.QRect(10, 310, 100, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.J2P.sizePolicy().hasHeightForWidth())
        self.J2P.setSizePolicy(sizePolicy)
        self.J2P.setMinimumSize(QtCore.QSize(0, 0))
        self.J2P.setMaximumSize(QtCore.QSize(190, 70))
        self.J2P.setStyleSheet("QPushButton {\n"
"    background-color: #3498db;  /* 按钮背景色 */\n"
"    color: white;  /* 文字颜色 */\n"
"    border-radius: 10px;  /* 圆角 */\n"
"    font-size: 16px;  /* 字体大小 */\n"
"    padding: 8px 16px;  /* 内边距 */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #2980b9; /* 悬停颜色 */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #1c6690; /* 按下颜色 */\n"
"}")
        self.J2P.setObjectName("J2P")
        self.J3P = QtWidgets.QPushButton(parent=self.centralwidget)
        self.J3P.setGeometry(QtCore.QRect(10, 360, 100, 40))
        self.J3P.setMinimumSize(QtCore.QSize(0, 0))
        self.J3P.setMaximumSize(QtCore.QSize(190, 70))
        self.J3P.setStyleSheet("QPushButton {\n"
"    background-color: #3498db;  /* 按钮背景色 */\n"
"    color: white;  /* 文字颜色 */\n"
"    border-radius: 10px;  /* 圆角 */\n"
"    font-size: 16px;  /* 字体大小 */\n"
"    padding: 8px 16px;  /* 内边距 */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #2980b9; /* 悬停颜色 */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #1c6690; /* 按下颜色 */\n"
"}")
        self.J3P.setObjectName("J3P")
        self.J4P = QtWidgets.QPushButton(parent=self.centralwidget)
        self.J4P.setGeometry(QtCore.QRect(10, 410, 100, 40))
        self.J4P.setMinimumSize(QtCore.QSize(0, 0))
        self.J4P.setMaximumSize(QtCore.QSize(190, 70))
        self.J4P.setStyleSheet("QPushButton {\n"
"    background-color: #3498db;  /* 按钮背景色 */\n"
"    color: white;  /* 文字颜色 */\n"
"    border-radius: 10px;  /* 圆角 */\n"
"    font-size: 16px;  /* 字体大小 */\n"
"    padding: 8px 16px;  /* 内边距 */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #2980b9; /* 悬停颜色 */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #1c6690; /* 按下颜色 */\n"
"}")
        self.J4P.setObjectName("J4P")
        self.J5P = QtWidgets.QPushButton(parent=self.centralwidget)
        self.J5P.setGeometry(QtCore.QRect(10, 460, 100, 40))
        self.J5P.setMinimumSize(QtCore.QSize(0, 0))
        self.J5P.setMaximumSize(QtCore.QSize(190, 70))
        self.J5P.setStyleSheet("QPushButton {\n"
"    background-color: #3498db;  /* 按钮背景色 */\n"
"    color: white;  /* 文字颜色 */\n"
"    border-radius: 10px;  /* 圆角 */\n"
"    font-size: 16px;  /* 字体大小 */\n"
"    padding: 8px 16px;  /* 内边距 */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #2980b9; /* 悬停颜色 */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #1c6690; /* 按下颜色 */\n"
"}")
        self.J5P.setObjectName("J5P")
        self.J6P = QtWidgets.QPushButton(parent=self.centralwidget)
        self.J6P.setGeometry(QtCore.QRect(10, 510, 100, 40))
        self.J6P.setMinimumSize(QtCore.QSize(0, 0))
        self.J6P.setMaximumSize(QtCore.QSize(190, 70))
        self.J6P.setStyleSheet("QPushButton {\n"
"    background-color: #3498db;  /* 按钮背景色 */\n"
"    color: white;  /* 文字颜色 */\n"
"    border-radius: 10px;  /* 圆角 */\n"
"    font-size: 16px;  /* 字体大小 */\n"
"    padding: 8px 16px;  /* 内边距 */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #2980b9; /* 悬停颜色 */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #1c6690; /* 按下颜色 */\n"
"}")
        self.J6P.setObjectName("J6P")
        self.J2N = QtWidgets.QPushButton(parent=self.centralwidget)
        self.J2N.setGeometry(QtCore.QRect(290, 310, 100, 40))
        self.J2N.setMinimumSize(QtCore.QSize(0, 0))
        self.J2N.setMaximumSize(QtCore.QSize(190, 70))
        self.J2N.setStyleSheet("QPushButton {\n"
"    background-color: #3498db;  /* 按钮背景色 */\n"
"    color: white;  /* 文字颜色 */\n"
"    border-radius: 10px;  /* 圆角 */\n"
"    font-size: 16px;  /* 字体大小 */\n"
"    padding: 8px 16px;  /* 内边距 */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #2980b9; /* 悬停颜色 */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #1c6690; /* 按下颜色 */\n"
"}")
        self.J2N.setObjectName("J2N")
        self.J3N = QtWidgets.QPushButton(parent=self.centralwidget)
        self.J3N.setGeometry(QtCore.QRect(290, 360, 100, 40))
        self.J3N.setMinimumSize(QtCore.QSize(0, 0))
        self.J3N.setMaximumSize(QtCore.QSize(190, 70))
        self.J3N.setStyleSheet("QPushButton {\n"
"    background-color: #3498db;  /* 按钮背景色 */\n"
"    color: white;  /* 文字颜色 */\n"
"    border-radius: 10px;  /* 圆角 */\n"
"    font-size: 16px;  /* 字体大小 */\n"
"    padding: 8px 16px;  /* 内边距 */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #2980b9; /* 悬停颜色 */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #1c6690; /* 按下颜色 */\n"
"}")
        self.J3N.setObjectName("J3N")
        self.J4N = QtWidgets.QPushButton(parent=self.centralwidget)
        self.J4N.setGeometry(QtCore.QRect(290, 410, 100, 40))
        self.J4N.setMinimumSize(QtCore.QSize(0, 0))
        self.J4N.setMaximumSize(QtCore.QSize(190, 70))
        self.J4N.setStyleSheet("QPushButton {\n"
"    background-color: #3498db;  /* 按钮背景色 */\n"
"    color: white;  /* 文字颜色 */\n"
"    border-radius: 10px;  /* 圆角 */\n"
"    font-size: 16px;  /* 字体大小 */\n"
"    padding: 8px 16px;  /* 内边距 */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #2980b9; /* 悬停颜色 */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #1c6690; /* 按下颜色 */\n"
"}")
        self.J4N.setObjectName("J4N")
        self.J5N = QtWidgets.QPushButton(parent=self.centralwidget)
        self.J5N.setGeometry(QtCore.QRect(290, 460, 100, 40))
        self.J5N.setMinimumSize(QtCore.QSize(0, 0))
        self.J5N.setMaximumSize(QtCore.QSize(190, 70))
        self.J5N.setStyleSheet("QPushButton {\n"
"    background-color: #3498db;  /* 按钮背景色 */\n"
"    color: white;  /* 文字颜色 */\n"
"    border-radius: 10px;  /* 圆角 */\n"
"    font-size: 16px;  /* 字体大小 */\n"
"    padding: 8px 16px;  /* 内边距 */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #2980b9; /* 悬停颜色 */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #1c6690; /* 按下颜色 */\n"
"}")
        self.J5N.setObjectName("J5N")
        self.J6N = QtWidgets.QPushButton(parent=self.centralwidget)
        self.J6N.setGeometry(QtCore.QRect(290, 510, 100, 40))
        self.J6N.setMinimumSize(QtCore.QSize(0, 0))
        self.J6N.setMaximumSize(QtCore.QSize(190, 70))
        self.J6N.setStyleSheet("QPushButton {\n"
"    background-color: #3498db;  /* 按钮背景色 */\n"
"    color: white;  /* 文字颜色 */\n"
"    border-radius: 10px;  /* 圆角 */\n"
"    font-size: 16px;  /* 字体大小 */\n"
"    padding: 8px 16px;  /* 内边距 */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #2980b9; /* 悬停颜色 */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #1c6690; /* 按下颜色 */\n"
"}")
        self.J6N.setObjectName("J6N")
        self.get_X = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.get_X.setGeometry(QtCore.QRect(590, 260, 120, 43))
        self.get_X.setMinimumSize(QtCore.QSize(0, 43))
        self.get_X.setStyleSheet("QLineEdit {\n"
"    background-color: #ecf0f1;  /* 浅灰色背景 */\n"
"    color: #2c3e50;  /* 文字颜色 */\n"
"    border: 2px solid #bdc3c7;  /* 默认边框 */\n"
"    border-radius: 10px;  /* 圆角 */\n"
"    font-size: 18px;  /* 字体大小，增加到18px */\n"
"    padding: 12px 16px;  /* 增大内边距，使文字更居中 */\n"
"    min-height: 15px;  /* 设置最小高度，保证输入框足够大 */ \n"
"    selection-background-color: #3498db;  /* 选中文字背景色 */\n"
"    selection-color: white;  /* 选中文字颜色 */\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid #95a5a6;  /* 悬停时边框颜色 */\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid #3498db;  /* 聚焦时边框变蓝 */\n"
"    background-color: white;  /* 聚焦时背景变白 */\n"
"}\n"
"QLineEdit:disabled {\n"
"    background-color: #bdc3c7;  /* 禁用时背景变灰 */\n"
"    color: #7f8c8d;  /* 禁用时字体颜色变暗 */\n"
"}\n"
"")
        self.get_X.setObjectName("get_X")
        self.get_Y = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.get_Y.setGeometry(QtCore.QRect(590, 310, 120, 43))
        self.get_Y.setMinimumSize(QtCore.QSize(0, 43))
        self.get_Y.setStyleSheet("QLineEdit {\n"
"    background-color: #ecf0f1;  /* 浅灰色背景 */\n"
"    color: #2c3e50;  /* 文字颜色 */\n"
"    border: 2px solid #bdc3c7;  /* 默认边框 */\n"
"    border-radius: 10px;  /* 圆角 */\n"
"    font-size: 18px;  /* 字体大小，增加到18px */\n"
"    padding: 12px 16px;  /* 增大内边距，使文字更居中 */\n"
"    min-height: 15px;  /* 设置最小高度，保证输入框足够大 */ \n"
"    selection-background-color: #3498db;  /* 选中文字背景色 */\n"
"    selection-color: white;  /* 选中文字颜色 */\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid #95a5a6;  /* 悬停时边框颜色 */\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid #3498db;  /* 聚焦时边框变蓝 */\n"
"    background-color: white;  /* 聚焦时背景变白 */\n"
"}\n"
"QLineEdit:disabled {\n"
"    background-color: #bdc3c7;  /* 禁用时背景变灰 */\n"
"    color: #7f8c8d;  /* 禁用时字体颜色变暗 */\n"
"}\n"
"")
        self.get_Y.setObjectName("get_Y")
        self.get_Z = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.get_Z.setGeometry(QtCore.QRect(590, 360, 120, 43))
        self.get_Z.setMinimumSize(QtCore.QSize(0, 43))
        self.get_Z.setStyleSheet("QLineEdit {\n"
"    background-color: #ecf0f1;  /* 浅灰色背景 */\n"
"    color: #2c3e50;  /* 文字颜色 */\n"
"    border: 2px solid #bdc3c7;  /* 默认边框 */\n"
"    border-radius: 10px;  /* 圆角 */\n"
"    font-size: 18px;  /* 字体大小，增加到18px */\n"
"    padding: 12px 16px;  /* 增大内边距，使文字更居中 */\n"
"    min-height: 15px;  /* 设置最小高度，保证输入框足够大 */ \n"
"    selection-background-color: #3498db;  /* 选中文字背景色 */\n"
"    selection-color: white;  /* 选中文字颜色 */\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid #95a5a6;  /* 悬停时边框颜色 */\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid #3498db;  /* 聚焦时边框变蓝 */\n"
"    background-color: white;  /* 聚焦时背景变白 */\n"
"}\n"
"QLineEdit:disabled {\n"
"    background-color: #bdc3c7;  /* 禁用时背景变灰 */\n"
"    color: #7f8c8d;  /* 禁用时字体颜色变暗 */\n"
"}\n"
"")
        self.get_Z.setObjectName("get_Z")
        self.get_Rx = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.get_Rx.setGeometry(QtCore.QRect(590, 410, 120, 43))
        self.get_Rx.setMinimumSize(QtCore.QSize(0, 43))
        self.get_Rx.setStyleSheet("QLineEdit {\n"
"    background-color: #ecf0f1;  /* 浅灰色背景 */\n"
"    color: #2c3e50;  /* 文字颜色 */\n"
"    border: 2px solid #bdc3c7;  /* 默认边框 */\n"
"    border-radius: 10px;  /* 圆角 */\n"
"    font-size: 18px;  /* 字体大小，增加到18px */\n"
"    padding: 12px 16px;  /* 增大内边距，使文字更居中 */\n"
"    min-height: 15px;  /* 设置最小高度，保证输入框足够大 */ \n"
"    selection-background-color: #3498db;  /* 选中文字背景色 */\n"
"    selection-color: white;  /* 选中文字颜色 */\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid #95a5a6;  /* 悬停时边框颜色 */\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid #3498db;  /* 聚焦时边框变蓝 */\n"
"    background-color: white;  /* 聚焦时背景变白 */\n"
"}\n"
"QLineEdit:disabled {\n"
"    background-color: #bdc3c7;  /* 禁用时背景变灰 */\n"
"    color: #7f8c8d;  /* 禁用时字体颜色变暗 */\n"
"}\n"
"")
        self.get_Rx.setObjectName("get_Rx")
        self.get_Ry = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.get_Ry.setGeometry(QtCore.QRect(590, 460, 120, 43))
        self.get_Ry.setMinimumSize(QtCore.QSize(0, 43))
        self.get_Ry.setStyleSheet("QLineEdit {\n"
"    background-color: #ecf0f1;  /* 浅灰色背景 */\n"
"    color: #2c3e50;  /* 文字颜色 */\n"
"    border: 2px solid #bdc3c7;  /* 默认边框 */\n"
"    border-radius: 10px;  /* 圆角 */\n"
"    font-size: 18px;  /* 字体大小，增加到18px */\n"
"    padding: 12px 16px;  /* 增大内边距，使文字更居中 */\n"
"    min-height: 15px;  /* 设置最小高度，保证输入框足够大 */ \n"
"    selection-background-color: #3498db;  /* 选中文字背景色 */\n"
"    selection-color: white;  /* 选中文字颜色 */\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid #95a5a6;  /* 悬停时边框颜色 */\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid #3498db;  /* 聚焦时边框变蓝 */\n"
"    background-color: white;  /* 聚焦时背景变白 */\n"
"}\n"
"QLineEdit:disabled {\n"
"    background-color: #bdc3c7;  /* 禁用时背景变灰 */\n"
"    color: #7f8c8d;  /* 禁用时字体颜色变暗 */\n"
"}\n"
"")
        self.get_Ry.setObjectName("get_Ry")
        self.get_Rz = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.get_Rz.setGeometry(QtCore.QRect(590, 510, 120, 43))
        self.get_Rz.setMinimumSize(QtCore.QSize(0, 43))
        self.get_Rz.setStyleSheet("QLineEdit {\n"
"    background-color: #ecf0f1;  /* 浅灰色背景 */\n"
"    color: #2c3e50;  /* 文字颜色 */\n"
"    border: 2px solid #bdc3c7;  /* 默认边框 */\n"
"    border-radius: 10px;  /* 圆角 */\n"
"    font-size: 18px;  /* 字体大小，增加到18px */\n"
"    padding: 12px 16px;  /* 增大内边距，使文字更居中 */\n"
"    min-height: 15px;  /* 设置最小高度，保证输入框足够大 */ \n"
"    selection-background-color: #3498db;  /* 选中文字背景色 */\n"
"    selection-color: white;  /* 选中文字颜色 */\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid #95a5a6;  /* 悬停时边框颜色 */\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid #3498db;  /* 聚焦时边框变蓝 */\n"
"    background-color: white;  /* 聚焦时背景变白 */\n"
"}\n"
"QLineEdit:disabled {\n"
"    background-color: #bdc3c7;  /* 禁用时背景变灰 */\n"
"    color: #7f8c8d;  /* 禁用时字体颜色变暗 */\n"
"}\n"
"")
        self.get_Rz.setObjectName("get_Rz")
        self.X = QtWidgets.QLabel(parent=self.centralwidget)
        self.X.setGeometry(QtCore.QRect(550, 260, 100, 40))
        self.X.setMinimumSize(QtCore.QSize(0, 0))
        self.X.setMaximumSize(QtCore.QSize(1111, 1111))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.X.setFont(font)
        self.X.setObjectName("X")
        self.Y = QtWidgets.QLabel(parent=self.centralwidget)
        self.Y.setGeometry(QtCore.QRect(550, 310, 100, 40))
        self.Y.setMinimumSize(QtCore.QSize(0, 0))
        self.Y.setMaximumSize(QtCore.QSize(1111, 1111))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Y.setFont(font)
        self.Y.setObjectName("Y")
        self.Z = QtWidgets.QLabel(parent=self.centralwidget)
        self.Z.setGeometry(QtCore.QRect(550, 360, 100, 40))
        self.Z.setMinimumSize(QtCore.QSize(0, 0))
        self.Z.setMaximumSize(QtCore.QSize(1111, 1111))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Z.setFont(font)
        self.Z.setObjectName("Z")
        self.Rx = QtWidgets.QLabel(parent=self.centralwidget)
        self.Rx.setGeometry(QtCore.QRect(550, 410, 100, 40))
        self.Rx.setMinimumSize(QtCore.QSize(0, 0))
        self.Rx.setMaximumSize(QtCore.QSize(1111, 1111))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Rx.setFont(font)
        self.Rx.setObjectName("Rx")
        self.Ry = QtWidgets.QLabel(parent=self.centralwidget)
        self.Ry.setGeometry(QtCore.QRect(550, 460, 100, 40))
        self.Ry.setMinimumSize(QtCore.QSize(0, 0))
        self.Ry.setMaximumSize(QtCore.QSize(1111, 1111))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Ry.setFont(font)
        self.Ry.setObjectName("Ry")
        self.X_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.X_6.setGeometry(QtCore.QRect(550, 510, 100, 40))
        self.X_6.setMinimumSize(QtCore.QSize(0, 0))
        self.X_6.setMaximumSize(QtCore.QSize(1111, 1111))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.X_6.setFont(font)
        self.X_6.setObjectName("X_6")
        self.XP = QtWidgets.QPushButton(parent=self.centralwidget)
        self.XP.setGeometry(QtCore.QRect(430, 260, 100, 40))
        self.XP.setMinimumSize(QtCore.QSize(0, 0))
        self.XP.setMaximumSize(QtCore.QSize(190, 70))
        self.XP.setStyleSheet("QPushButton {\n"
"    background-color: #2ecc71;  /* 绿色背景色 */\n"
"    color: white;  /* 文字颜色 */\n"
"    border-radius: 10px;  /* 圆角 */\n"
"    font-size: 16px;  /* 字体大小 */\n"
"    padding: 8px 16px;  /* 内边距 */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #27ae60; /* 悬停时颜色 */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #1e8449; /* 按下时颜色 */\n"
"}\n"
"")
        self.XP.setObjectName("XP")
        self.YP = QtWidgets.QPushButton(parent=self.centralwidget)
        self.YP.setGeometry(QtCore.QRect(430, 310, 100, 40))
        self.YP.setMinimumSize(QtCore.QSize(0, 0))
        self.YP.setMaximumSize(QtCore.QSize(190, 70))
        self.YP.setStyleSheet("QPushButton {\n"
"    background-color: #2ecc71;  /* 绿色背景色 */\n"
"    color: white;  /* 文字颜色 */\n"
"    border-radius: 10px;  /* 圆角 */\n"
"    font-size: 16px;  /* 字体大小 */\n"
"    padding: 8px 16px;  /* 内边距 */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #27ae60; /* 悬停时颜色 */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #1e8449; /* 按下时颜色 */\n"
"}\n"
"")
        self.YP.setObjectName("YP")
        self.ZP = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ZP.setGeometry(QtCore.QRect(430, 360, 100, 40))
        self.ZP.setMinimumSize(QtCore.QSize(0, 0))
        self.ZP.setMaximumSize(QtCore.QSize(190, 70))
        self.ZP.setStyleSheet("QPushButton {\n"
"    background-color: #2ecc71;  /* 绿色背景色 */\n"
"    color: white;  /* 文字颜色 */\n"
"    border-radius: 10px;  /* 圆角 */\n"
"    font-size: 16px;  /* 字体大小 */\n"
"    padding: 8px 16px;  /* 内边距 */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #27ae60; /* 悬停时颜色 */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #1e8449; /* 按下时颜色 */\n"
"}\n"
"")
        self.ZP.setObjectName("ZP")
        self.RxP = QtWidgets.QPushButton(parent=self.centralwidget)
        self.RxP.setGeometry(QtCore.QRect(430, 410, 100, 40))
        self.RxP.setMinimumSize(QtCore.QSize(0, 0))
        self.RxP.setMaximumSize(QtCore.QSize(190, 70))
        self.RxP.setStyleSheet("QPushButton {\n"
"    background-color: #2ecc71;  /* 绿色背景色 */\n"
"    color: white;  /* 文字颜色 */\n"
"    border-radius: 10px;  /* 圆角 */\n"
"    font-size: 16px;  /* 字体大小 */\n"
"    padding: 8px 16px;  /* 内边距 */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #27ae60; /* 悬停时颜色 */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #1e8449; /* 按下时颜色 */\n"
"}\n"
"")
        self.RxP.setObjectName("RxP")
        self.RyP = QtWidgets.QPushButton(parent=self.centralwidget)
        self.RyP.setGeometry(QtCore.QRect(430, 460, 100, 40))
        self.RyP.setMinimumSize(QtCore.QSize(0, 0))
        self.RyP.setMaximumSize(QtCore.QSize(190, 70))
        self.RyP.setStyleSheet("QPushButton {\n"
"    background-color: #2ecc71;  /* 绿色背景色 */\n"
"    color: white;  /* 文字颜色 */\n"
"    border-radius: 10px;  /* 圆角 */\n"
"    font-size: 16px;  /* 字体大小 */\n"
"    padding: 8px 16px;  /* 内边距 */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #27ae60; /* 悬停时颜色 */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #1e8449; /* 按下时颜色 */\n"
"}\n"
"")
        self.RyP.setObjectName("RyP")
        self.RzP = QtWidgets.QPushButton(parent=self.centralwidget)
        self.RzP.setGeometry(QtCore.QRect(430, 510, 100, 40))
        self.RzP.setMinimumSize(QtCore.QSize(0, 0))
        self.RzP.setMaximumSize(QtCore.QSize(190, 70))
        self.RzP.setStyleSheet("QPushButton {\n"
"    background-color: #2ecc71;  /* 绿色背景色 */\n"
"    color: white;  /* 文字颜色 */\n"
"    border-radius: 10px;  /* 圆角 */\n"
"    font-size: 16px;  /* 字体大小 */\n"
"    padding: 8px 16px;  /* 内边距 */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #27ae60; /* 悬停时颜色 */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #1e8449; /* 按下时颜色 */\n"
"}\n"
"")
        self.RzP.setObjectName("RzP")
        self.XN = QtWidgets.QPushButton(parent=self.centralwidget)
        self.XN.setGeometry(QtCore.QRect(730, 250, 100, 40))
        self.XN.setMinimumSize(QtCore.QSize(0, 0))
        self.XN.setStyleSheet("QPushButton {\n"
"    background-color: #2ecc71;  /* 绿色背景色 */\n"
"    color: white;  /* 文字颜色 */\n"
"    border-radius: 10px;  /* 圆角 */\n"
"    font-size: 16px;  /* 字体大小 */\n"
"    padding: 8px 16px;  /* 内边距 */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #27ae60; /* 悬停时颜色 */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #1e8449; /* 按下时颜色 */\n"
"}\n"
"")
        self.XN.setObjectName("XN")
        self.YN = QtWidgets.QPushButton(parent=self.centralwidget)
        self.YN.setGeometry(QtCore.QRect(730, 300, 100, 40))
        self.YN.setMinimumSize(QtCore.QSize(0, 0))
        self.YN.setStyleSheet("QPushButton {\n"
"    background-color: #2ecc71;  /* 绿色背景色 */\n"
"    color: white;  /* 文字颜色 */\n"
"    border-radius: 10px;  /* 圆角 */\n"
"    font-size: 16px;  /* 字体大小 */\n"
"    padding: 8px 16px;  /* 内边距 */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #27ae60; /* 悬停时颜色 */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #1e8449; /* 按下时颜色 */\n"
"}\n"
"")
        self.YN.setObjectName("YN")
        self.ZN = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ZN.setGeometry(QtCore.QRect(730, 350, 100, 40))
        self.ZN.setMinimumSize(QtCore.QSize(0, 0))
        self.ZN.setStyleSheet("QPushButton {\n"
"    background-color: #2ecc71;  /* 绿色背景色 */\n"
"    color: white;  /* 文字颜色 */\n"
"    border-radius: 10px;  /* 圆角 */\n"
"    font-size: 16px;  /* 字体大小 */\n"
"    padding: 8px 16px;  /* 内边距 */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #27ae60; /* 悬停时颜色 */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #1e8449; /* 按下时颜色 */\n"
"}\n"
"")
        self.ZN.setObjectName("ZN")
        self.RxN = QtWidgets.QPushButton(parent=self.centralwidget)
        self.RxN.setGeometry(QtCore.QRect(730, 400, 100, 40))
        self.RxN.setMinimumSize(QtCore.QSize(0, 0))
        self.RxN.setStyleSheet("QPushButton {\n"
"    background-color: #2ecc71;  /* 绿色背景色 */\n"
"    color: white;  /* 文字颜色 */\n"
"    border-radius: 10px;  /* 圆角 */\n"
"    font-size: 16px;  /* 字体大小 */\n"
"    padding: 8px 16px;  /* 内边距 */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #27ae60; /* 悬停时颜色 */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #1e8449; /* 按下时颜色 */\n"
"}\n"
"")
        self.RxN.setObjectName("RxN")
        self.RyN = QtWidgets.QPushButton(parent=self.centralwidget)
        self.RyN.setGeometry(QtCore.QRect(730, 450, 100, 40))
        self.RyN.setMinimumSize(QtCore.QSize(0, 0))
        self.RyN.setStyleSheet("QPushButton {\n"
"    background-color: #2ecc71;  /* 绿色背景色 */\n"
"    color: white;  /* 文字颜色 */\n"
"    border-radius: 10px;  /* 圆角 */\n"
"    font-size: 16px;  /* 字体大小 */\n"
"    padding: 8px 16px;  /* 内边距 */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #27ae60; /* 悬停时颜色 */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #1e8449; /* 按下时颜色 */\n"
"}\n"
"")
        self.RyN.setObjectName("RyN")
        self.RzN = QtWidgets.QPushButton(parent=self.centralwidget)
        self.RzN.setGeometry(QtCore.QRect(730, 500, 100, 40))
        self.RzN.setMinimumSize(QtCore.QSize(0, 0))
        self.RzN.setStyleSheet("QPushButton {\n"
"    background-color: #2ecc71;  /* 绿色背景色 */\n"
"    color: white;  /* 文字颜色 */\n"
"    border-radius: 10px;  /* 圆角 */\n"
"    font-size: 16px;  /* 字体大小 */\n"
"    padding: 8px 16px;  /* 内边距 */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #27ae60; /* 悬停时颜色 */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #1e8449; /* 按下时颜色 */\n"
"}\n"
"")
        self.RzN.setObjectName("RzN")
        self.runScriptBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.runScriptBtn.setGeometry(QtCore.QRect(560, 110, 100, 40))
        self.runScriptBtn.setMinimumSize(QtCore.QSize(0, 0))
        self.runScriptBtn.setStyleSheet("QPushButton {\n"
"    background-color: #228B22;  /* 深绿色背景色 */\n"
"    color: white;  /* 文字颜色 */\n"
"    border-radius: 10px;  /* 圆角 */\n"
"    font-size: 16px;  /* 字体大小 */\n"
"    padding: 8px 16px;  /* 内边距 */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #1E7B1E; /* 悬停时颜色，略深 */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #166D16; /* 按下时颜色，更深 */\n"
"}\n"
"")
        self.runScriptBtn.setObjectName("runScriptBtn")
        self.pauseBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pauseBtn.setGeometry(QtCore.QRect(560, 160, 100, 40))
        self.pauseBtn.setMinimumSize(QtCore.QSize(0, 0))
        self.pauseBtn.setStyleSheet("QPushButton {\n"
"    background-color: #F7DC6F;  /* 柔和的淡黄色 */\n"
"    color: black;  /* 文字颜色（黑色，提高可读性） */\n"
"    border-radius: 10px;  /* 圆角 */\n"
"    font-size: 16px;  /* 字体大小 */\n"
"    padding: 8px 16px;  /* 内边距 */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #F4D03F; /* 悬停时颜色，更亮的黄色 */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #D4AC0D; /* 按下时颜色，稍深 */\n"
"}\n"
"")
        self.pauseBtn.setObjectName("pauseBtn")
        self.continueBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.continueBtn.setGeometry(QtCore.QRect(670, 160, 100, 40))
        self.continueBtn.setMinimumSize(QtCore.QSize(0, 0))
        self.continueBtn.setStyleSheet("QPushButton {\n"
"    background-color: #E67E22;  /* 亮橙色 */\n"
"    color: white;  /* 文字颜色（白色，增强对比度） */\n"
"    border-radius: 10px;  /* 圆角 */\n"
"    font-size: 16px;  /* 字体大小 */\n"
"    padding: 8px 16px;  /* 内边距 */\n"
"    border: none; /* 去掉边框，现代感更强 */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #D35400; /* 悬停时颜色，深橙色 */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #A04000; /* 按下时颜色，更深的橙色 */\n"
"}\n"
"")
        self.continueBtn.setObjectName("continueBtn")
        self.stopBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.stopBtn.setGeometry(QtCore.QRect(670, 110, 100, 40))
        self.stopBtn.setMinimumSize(QtCore.QSize(0, 0))
        self.stopBtn.setStyleSheet("QPushButton {\n"
"    background-color: #B22222;  /* 深红色背景 */\n"
"    color: white;  /* 文字颜色 */\n"
"    border-radius: 10px;  /* 圆角 */\n"
"    font-size: 16px;  /* 字体大小 */\n"
"    padding: 8px 16px;  /* 内边距 */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #8B1A1A; /* 悬停时颜色，稍深 */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #701010; /* 按下时颜色，更深 */\n"
"}\n"
"")
        self.stopBtn.setIconSize(QtCore.QSize(12, 12))
        self.stopBtn.setObjectName("stopBtn")
        self.scriptNameInput = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.scriptNameInput.setGeometry(QtCore.QRect(570, 40, 191, 51))
        self.scriptNameInput.setMinimumSize(QtCore.QSize(0, 38))
        self.scriptNameInput.setStyleSheet("QLineEdit {\n"
"    background-color: #ecf0f1;  /* 浅灰色背景 */\n"
"    color: #2c3e50;  /* 文字颜色 */\n"
"    border: 2px solid #bdc3c7;  /* 默认边框 */\n"
"    border-radius: 10px;  /* 圆角 */\n"
"    font-size: 18px;  /* 字体大小，增加到18px */\n"
"    padding: 12px 16px;  /* 增大内边距，使文字更居中 */\n"
"    min-height: 10px;  /* 设置最小高度，保证输入框足够大 */ \n"
"    selection-background-color: #3498db;  /* 选中文字背景色 */\n"
"    selection-color: white;  /* 选中文字颜色 */\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid #95a5a6;  /* 悬停时边框颜色 */\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid #3498db;  /* 聚焦时边框变蓝 */\n"
"    background-color: white;  /* 聚焦时背景变白 */\n"
"}\n"
"QLineEdit:disabled {\n"
"    background-color: #bdc3c7;  /* 禁用时背景变灰 */\n"
"    color: #7f8c8d;  /* 禁用时字体颜色变暗 */\n"
"}\n"
"")
        self.scriptNameInput.setObjectName("scriptNameInput")
        self.Script_txt = QtWidgets.QLabel(parent=self.centralwidget)
        self.Script_txt.setGeometry(QtCore.QRect(500, 50, 61, 40))
        self.Script_txt.setMinimumSize(QtCore.QSize(0, 0))
        self.Script_txt.setMaximumSize(QtCore.QSize(1111, 1111))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Script_txt.setFont(font)
        self.Script_txt.setObjectName("Script_txt")
        self.Move_txt = QtWidgets.QLabel(parent=self.centralwidget)
        self.Move_txt.setGeometry(QtCore.QRect(930, 40, 211, 40))
        self.Move_txt.setMinimumSize(QtCore.QSize(0, 0))
        self.Move_txt.setMaximumSize(QtCore.QSize(1111, 1111))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Move_txt.setFont(font)
        self.Move_txt.setObjectName("Move_txt")
        self.M_J1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.M_J1.setGeometry(QtCore.QRect(910, 110, 21, 40))
        self.M_J1.setMinimumSize(QtCore.QSize(0, 0))
        self.M_J1.setMaximumSize(QtCore.QSize(16777215, 1111))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.M_J1.setFont(font)
        self.M_J1.setStyleSheet("")
        self.M_J1.setObjectName("M_J1")
        self.M_J2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.M_J2.setGeometry(QtCore.QRect(910, 160, 21, 40))
        self.M_J2.setMinimumSize(QtCore.QSize(0, 0))
        self.M_J2.setMaximumSize(QtCore.QSize(16777215, 1111))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.M_J2.setFont(font)
        self.M_J2.setStyleSheet("")
        self.M_J2.setObjectName("M_J2")
        self.M_J3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.M_J3.setGeometry(QtCore.QRect(910, 210, 21, 40))
        self.M_J3.setMinimumSize(QtCore.QSize(0, 0))
        self.M_J3.setMaximumSize(QtCore.QSize(16777215, 1111))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.M_J3.setFont(font)
        self.M_J3.setStyleSheet("")
        self.M_J3.setObjectName("M_J3")
        self.M_J4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.M_J4.setGeometry(QtCore.QRect(910, 260, 31, 40))
        self.M_J4.setMinimumSize(QtCore.QSize(0, 0))
        self.M_J4.setMaximumSize(QtCore.QSize(16777215, 1111))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.M_J4.setFont(font)
        self.M_J4.setStyleSheet("")
        self.M_J4.setObjectName("M_J4")
        self.M_J5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.M_J5.setGeometry(QtCore.QRect(910, 310, 31, 40))
        self.M_J5.setMinimumSize(QtCore.QSize(0, 0))
        self.M_J5.setMaximumSize(QtCore.QSize(16777215, 1111))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.M_J5.setFont(font)
        self.M_J5.setStyleSheet("")
        self.M_J5.setObjectName("M_J5")
        self.M_J6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.M_J6.setGeometry(QtCore.QRect(910, 360, 31, 40))
        self.M_J6.setMinimumSize(QtCore.QSize(0, 0))
        self.M_J6.setMaximumSize(QtCore.QSize(16777215, 1111))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.M_J6.setFont(font)
        self.M_J6.setStyleSheet("")
        self.M_J6.setObjectName("M_J6")
        self.get_M_J1 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.get_M_J1.setGeometry(QtCore.QRect(950, 110, 120, 43))
        self.get_M_J1.setMinimumSize(QtCore.QSize(0, 43))
        self.get_M_J1.setStyleSheet("QLineEdit {\n"
"    background-color: #ecf0f1;  /* 浅灰色背景 */\n"
"    color: #2c3e50;  /* 文字颜色 */\n"
"    border: 2px solid #bdc3c7;  /* 默认边框 */\n"
"    border-radius: 10px;  /* 圆角 */\n"
"    font-size: 18px;  /* 字体大小，增加到18px */\n"
"    padding: 12px 16px;  /* 增大内边距，使文字更居中 */\n"
"    min-height: 15px;  /* 设置最小高度，保证输入框足够大 */ \n"
"    selection-background-color: #3498db;  /* 选中文字背景色 */\n"
"    selection-color: white;  /* 选中文字颜色 */\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid #95a5a6;  /* 悬停时边框颜色 */\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid #3498db;  /* 聚焦时边框变蓝 */\n"
"    background-color: white;  /* 聚焦时背景变白 */\n"
"}\n"
"QLineEdit:disabled {\n"
"    background-color: #bdc3c7;  /* 禁用时背景变灰 */\n"
"    color: #7f8c8d;  /* 禁用时字体颜色变暗 */\n"
"}\n"
"")
        self.get_M_J1.setObjectName("get_M_J1")
        self.get_M_J2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.get_M_J2.setGeometry(QtCore.QRect(950, 160, 120, 43))
        self.get_M_J2.setMinimumSize(QtCore.QSize(0, 43))
        self.get_M_J2.setStyleSheet("QLineEdit {\n"
"    background-color: #ecf0f1;  /* 浅灰色背景 */\n"
"    color: #2c3e50;  /* 文字颜色 */\n"
"    border: 2px solid #bdc3c7;  /* 默认边框 */\n"
"    border-radius: 10px;  /* 圆角 */\n"
"    font-size: 18px;  /* 字体大小，增加到18px */\n"
"    padding: 12px 16px;  /* 增大内边距，使文字更居中 */\n"
"    min-height: 15px;  /* 设置最小高度，保证输入框足够大 */ \n"
"    selection-background-color: #3498db;  /* 选中文字背景色 */\n"
"    selection-color: white;  /* 选中文字颜色 */\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid #95a5a6;  /* 悬停时边框颜色 */\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid #3498db;  /* 聚焦时边框变蓝 */\n"
"    background-color: white;  /* 聚焦时背景变白 */\n"
"}\n"
"QLineEdit:disabled {\n"
"    background-color: #bdc3c7;  /* 禁用时背景变灰 */\n"
"    color: #7f8c8d;  /* 禁用时字体颜色变暗 */\n"
"}\n"
"")
        self.get_M_J2.setObjectName("get_M_J2")
        self.get_M_J3 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.get_M_J3.setGeometry(QtCore.QRect(950, 210, 120, 43))
        self.get_M_J3.setMinimumSize(QtCore.QSize(0, 43))
        self.get_M_J3.setStyleSheet("QLineEdit {\n"
"    background-color: #ecf0f1;  /* 浅灰色背景 */\n"
"    color: #2c3e50;  /* 文字颜色 */\n"
"    border: 2px solid #bdc3c7;  /* 默认边框 */\n"
"    border-radius: 10px;  /* 圆角 */\n"
"    font-size: 18px;  /* 字体大小，增加到18px */\n"
"    padding: 12px 16px;  /* 增大内边距，使文字更居中 */\n"
"    min-height: 15px;  /* 设置最小高度，保证输入框足够大 */ \n"
"    selection-background-color: #3498db;  /* 选中文字背景色 */\n"
"    selection-color: white;  /* 选中文字颜色 */\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid #95a5a6;  /* 悬停时边框颜色 */\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid #3498db;  /* 聚焦时边框变蓝 */\n"
"    background-color: white;  /* 聚焦时背景变白 */\n"
"}\n"
"QLineEdit:disabled {\n"
"    background-color: #bdc3c7;  /* 禁用时背景变灰 */\n"
"    color: #7f8c8d;  /* 禁用时字体颜色变暗 */\n"
"}\n"
"")
        self.get_M_J3.setObjectName("get_M_J3")
        self.get_M_J4 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.get_M_J4.setGeometry(QtCore.QRect(950, 260, 120, 43))
        self.get_M_J4.setMinimumSize(QtCore.QSize(0, 43))
        self.get_M_J4.setStyleSheet("QLineEdit {\n"
"    background-color: #ecf0f1;  /* 浅灰色背景 */\n"
"    color: #2c3e50;  /* 文字颜色 */\n"
"    border: 2px solid #bdc3c7;  /* 默认边框 */\n"
"    border-radius: 10px;  /* 圆角 */\n"
"    font-size: 18px;  /* 字体大小，增加到18px */\n"
"    padding: 12px 16px;  /* 增大内边距，使文字更居中 */\n"
"    min-height: 15px;  /* 设置最小高度，保证输入框足够大 */ \n"
"    selection-background-color: #3498db;  /* 选中文字背景色 */\n"
"    selection-color: white;  /* 选中文字颜色 */\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid #95a5a6;  /* 悬停时边框颜色 */\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid #3498db;  /* 聚焦时边框变蓝 */\n"
"    background-color: white;  /* 聚焦时背景变白 */\n"
"}\n"
"QLineEdit:disabled {\n"
"    background-color: #bdc3c7;  /* 禁用时背景变灰 */\n"
"    color: #7f8c8d;  /* 禁用时字体颜色变暗 */\n"
"}\n"
"")
        self.get_M_J4.setObjectName("get_M_J4")
        self.get_M_J5 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.get_M_J5.setGeometry(QtCore.QRect(950, 310, 120, 43))
        self.get_M_J5.setMinimumSize(QtCore.QSize(0, 43))
        self.get_M_J5.setStyleSheet("QLineEdit {\n"
"    background-color: #ecf0f1;  /* 浅灰色背景 */\n"
"    color: #2c3e50;  /* 文字颜色 */\n"
"    border: 2px solid #bdc3c7;  /* 默认边框 */\n"
"    border-radius: 10px;  /* 圆角 */\n"
"    font-size: 18px;  /* 字体大小，增加到18px */\n"
"    padding: 12px 16px;  /* 增大内边距，使文字更居中 */\n"
"    min-height: 15px;  /* 设置最小高度，保证输入框足够大 */ \n"
"    selection-background-color: #3498db;  /* 选中文字背景色 */\n"
"    selection-color: white;  /* 选中文字颜色 */\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid #95a5a6;  /* 悬停时边框颜色 */\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid #3498db;  /* 聚焦时边框变蓝 */\n"
"    background-color: white;  /* 聚焦时背景变白 */\n"
"}\n"
"QLineEdit:disabled {\n"
"    background-color: #bdc3c7;  /* 禁用时背景变灰 */\n"
"    color: #7f8c8d;  /* 禁用时字体颜色变暗 */\n"
"}\n"
"")
        self.get_M_J5.setObjectName("get_M_J5")
        self.get_M_J6 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.get_M_J6.setGeometry(QtCore.QRect(950, 360, 120, 43))
        self.get_M_J6.setMinimumSize(QtCore.QSize(0, 43))
        self.get_M_J6.setStyleSheet("QLineEdit {\n"
"    background-color: #ecf0f1;  /* 浅灰色背景 */\n"
"    color: #2c3e50;  /* 文字颜色 */\n"
"    border: 2px solid #bdc3c7;  /* 默认边框 */\n"
"    border-radius: 10px;  /* 圆角 */\n"
"    font-size: 18px;  /* 字体大小，增加到18px */\n"
"    padding: 12px 16px;  /* 增大内边距，使文字更居中 */\n"
"    min-height: 15px;  /* 设置最小高度，保证输入框足够大 */ \n"
"    selection-background-color: #3498db;  /* 选中文字背景色 */\n"
"    selection-color: white;  /* 选中文字颜色 */\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid #95a5a6;  /* 悬停时边框颜色 */\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid #3498db;  /* 聚焦时边框变蓝 */\n"
"    background-color: white;  /* 聚焦时背景变白 */\n"
"}\n"
"QLineEdit:disabled {\n"
"    background-color: #bdc3c7;  /* 禁用时背景变灰 */\n"
"    color: #7f8c8d;  /* 禁用时字体颜色变暗 */\n"
"}\n"
"")
        self.get_M_J6.setObjectName("get_M_J6")
        self.Acc_text = QtWidgets.QLabel(parent=self.centralwidget)
        self.Acc_text.setGeometry(QtCore.QRect(890, 410, 211, 41))
        self.Acc_text.setMinimumSize(QtCore.QSize(0, 0))
        self.Acc_text.setMaximumSize(QtCore.QSize(16777215, 1111))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Acc_text.setFont(font)
        self.Acc_text.setStyleSheet("")
        self.Acc_text.setObjectName("Acc_text")
        self.Vel_text = QtWidgets.QLabel(parent=self.centralwidget)
        self.Vel_text.setGeometry(QtCore.QRect(890, 460, 221, 40))
        self.Vel_text.setMinimumSize(QtCore.QSize(0, 0))
        self.Vel_text.setMaximumSize(QtCore.QSize(16777215, 1111))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Vel_text.setFont(font)
        self.Vel_text.setStyleSheet("")
        self.Vel_text.setObjectName("Vel_text")
        self.get_Acc_Rate = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.get_Acc_Rate.setGeometry(QtCore.QRect(1120, 410, 120, 43))
        self.get_Acc_Rate.setMinimumSize(QtCore.QSize(0, 43))
        self.get_Acc_Rate.setStyleSheet("QLineEdit {\n"
"    background-color: #ecf0f1;  /* 浅灰色背景 */\n"
"    color: #2c3e50;  /* 文字颜色 */\n"
"    border: 2px solid #bdc3c7;  /* 默认边框 */\n"
"    border-radius: 10px;  /* 圆角 */\n"
"    font-size: 18px;  /* 字体大小，增加到18px */\n"
"    padding: 12px 16px;  /* 增大内边距，使文字更居中 */\n"
"    min-height: 15px;  /* 设置最小高度，保证输入框足够大 */ \n"
"    selection-background-color: #3498db;  /* 选中文字背景色 */\n"
"    selection-color: white;  /* 选中文字颜色 */\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid #95a5a6;  /* 悬停时边框颜色 */\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid #3498db;  /* 聚焦时边框变蓝 */\n"
"    background-color: white;  /* 聚焦时背景变白 */\n"
"}\n"
"QLineEdit:disabled {\n"
"    background-color: #bdc3c7;  /* 禁用时背景变灰 */\n"
"    color: #7f8c8d;  /* 禁用时字体颜色变暗 */\n"
"}\n"
"")
        self.get_Acc_Rate.setObjectName("get_Acc_Rate")
        self.get_M_Vel_Rate = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.get_M_Vel_Rate.setGeometry(QtCore.QRect(1120, 460, 120, 43))
        self.get_M_Vel_Rate.setMinimumSize(QtCore.QSize(0, 43))
        self.get_M_Vel_Rate.setStyleSheet("QLineEdit {\n"
"    background-color: #ecf0f1;  /* 浅灰色背景 */\n"
"    color: #2c3e50;  /* 文字颜色 */\n"
"    border: 2px solid #bdc3c7;  /* 默认边框 */\n"
"    border-radius: 10px;  /* 圆角 */\n"
"    font-size: 18px;  /* 字体大小，增加到18px */\n"
"    padding: 12px 16px;  /* 增大内边距，使文字更居中 */\n"
"    min-height: 15px;  /* 设置最小高度，保证输入框足够大 */ \n"
"    selection-background-color: #3498db;  /* 选中文字背景色 */\n"
"    selection-color: white;  /* 选中文字颜色 */\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid #95a5a6;  /* 悬停时边框颜色 */\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid #3498db;  /* 聚焦时边框变蓝 */\n"
"    background-color: white;  /* 聚焦时背景变白 */\n"
"}\n"
"QLineEdit:disabled {\n"
"    background-color: #bdc3c7;  /* 禁用时背景变灰 */\n"
"    color: #7f8c8d;  /* 禁用时字体颜色变暗 */\n"
"}\n"
"")
        self.get_M_Vel_Rate.setObjectName("get_M_Vel_Rate")
        self.Move_J_btm = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Move_J_btm.setGeometry(QtCore.QRect(970, 510, 100, 40))
        self.Move_J_btm.setMinimumSize(QtCore.QSize(0, 0))
        self.Move_J_btm.setMaximumSize(QtCore.QSize(190, 70))
        self.Move_J_btm.setStyleSheet("QPushButton {\n"
"    background-color: #A9DFBF;  /* 柔和的浅绿色 */\n"
"    color: black;  /* 文字颜色（黑色，提高可读性） */\n"
"    border-radius: 10px;  /* 圆角 */\n"
"    font-size: 16px;  /* 字体大小 */\n"
"    padding: 8px 16px;  /* 内边距 */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #7DCEA0; /* 悬停时颜色，更亮的绿色 */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #52BE80; /* 按下时颜色，稍深 */\n"
"}\n"
"")
        self.Move_J_btm.setObjectName("Move_J_btm")
        self.get_M_X = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.get_M_X.setGeometry(QtCore.QRect(1120, 110, 120, 43))
        self.get_M_X.setMinimumSize(QtCore.QSize(0, 43))
        self.get_M_X.setStyleSheet("QLineEdit {\n"
"    background-color: #ecf0f1;  /* 浅灰色背景 */\n"
"    color: #2c3e50;  /* 文字颜色 */\n"
"    border: 2px solid #bdc3c7;  /* 默认边框 */\n"
"    border-radius: 10px;  /* 圆角 */\n"
"    font-size: 18px;  /* 字体大小，增加到18px */\n"
"    padding: 12px 16px;  /* 增大内边距，使文字更居中 */\n"
"    min-height: 15px;  /* 设置最小高度，保证输入框足够大 */ \n"
"    selection-background-color: #3498db;  /* 选中文字背景色 */\n"
"    selection-color: white;  /* 选中文字颜色 */\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid #95a5a6;  /* 悬停时边框颜色 */\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid #3498db;  /* 聚焦时边框变蓝 */\n"
"    background-color: white;  /* 聚焦时背景变白 */\n"
"}\n"
"QLineEdit:disabled {\n"
"    background-color: #bdc3c7;  /* 禁用时背景变灰 */\n"
"    color: #7f8c8d;  /* 禁用时字体颜色变暗 */\n"
"}\n"
"")
        self.get_M_X.setObjectName("get_M_X")
        self.M_X = QtWidgets.QLabel(parent=self.centralwidget)
        self.M_X.setGeometry(QtCore.QRect(1090, 110, 21, 40))
        self.M_X.setMinimumSize(QtCore.QSize(0, 0))
        self.M_X.setMaximumSize(QtCore.QSize(16777215, 1111))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.M_X.setFont(font)
        self.M_X.setStyleSheet("")
        self.M_X.setObjectName("M_X")
        self.M_Y = QtWidgets.QLabel(parent=self.centralwidget)
        self.M_Y.setGeometry(QtCore.QRect(1090, 160, 21, 40))
        self.M_Y.setMinimumSize(QtCore.QSize(0, 0))
        self.M_Y.setMaximumSize(QtCore.QSize(16777215, 1111))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.M_Y.setFont(font)
        self.M_Y.setStyleSheet("")
        self.M_Y.setObjectName("M_Y")
        self.M_Z = QtWidgets.QLabel(parent=self.centralwidget)
        self.M_Z.setGeometry(QtCore.QRect(1090, 210, 21, 40))
        self.M_Z.setMinimumSize(QtCore.QSize(0, 0))
        self.M_Z.setMaximumSize(QtCore.QSize(16777215, 1111))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.M_Z.setFont(font)
        self.M_Z.setStyleSheet("")
        self.M_Z.setObjectName("M_Z")
        self.M_Rx = QtWidgets.QLabel(parent=self.centralwidget)
        self.M_Rx.setGeometry(QtCore.QRect(1080, 260, 31, 40))
        self.M_Rx.setMinimumSize(QtCore.QSize(0, 0))
        self.M_Rx.setMaximumSize(QtCore.QSize(16777215, 1111))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.M_Rx.setFont(font)
        self.M_Rx.setStyleSheet("")
        self.M_Rx.setObjectName("M_Rx")
        self.M_Ry = QtWidgets.QLabel(parent=self.centralwidget)
        self.M_Ry.setGeometry(QtCore.QRect(1080, 310, 31, 40))
        self.M_Ry.setMinimumSize(QtCore.QSize(0, 0))
        self.M_Ry.setMaximumSize(QtCore.QSize(16777215, 1111))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.M_Ry.setFont(font)
        self.M_Ry.setStyleSheet("")
        self.M_Ry.setObjectName("M_Ry")
        self.M_Rz = QtWidgets.QLabel(parent=self.centralwidget)
        self.M_Rz.setGeometry(QtCore.QRect(1080, 360, 21, 40))
        self.M_Rz.setMinimumSize(QtCore.QSize(0, 0))
        self.M_Rz.setMaximumSize(QtCore.QSize(16777215, 1111))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.M_Rz.setFont(font)
        self.M_Rz.setStyleSheet("")
        self.M_Rz.setObjectName("M_Rz")
        self.get_M_Y = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.get_M_Y.setGeometry(QtCore.QRect(1120, 160, 120, 43))
        self.get_M_Y.setMinimumSize(QtCore.QSize(0, 43))
        self.get_M_Y.setStyleSheet("QLineEdit {\n"
"    background-color: #ecf0f1;  /* 浅灰色背景 */\n"
"    color: #2c3e50;  /* 文字颜色 */\n"
"    border: 2px solid #bdc3c7;  /* 默认边框 */\n"
"    border-radius: 10px;  /* 圆角 */\n"
"    font-size: 18px;  /* 字体大小，增加到18px */\n"
"    padding: 12px 16px;  /* 增大内边距，使文字更居中 */\n"
"    min-height: 15px;  /* 设置最小高度，保证输入框足够大 */ \n"
"    selection-background-color: #3498db;  /* 选中文字背景色 */\n"
"    selection-color: white;  /* 选中文字颜色 */\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid #95a5a6;  /* 悬停时边框颜色 */\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid #3498db;  /* 聚焦时边框变蓝 */\n"
"    background-color: white;  /* 聚焦时背景变白 */\n"
"}\n"
"QLineEdit:disabled {\n"
"    background-color: #bdc3c7;  /* 禁用时背景变灰 */\n"
"    color: #7f8c8d;  /* 禁用时字体颜色变暗 */\n"
"}\n"
"")
        self.get_M_Y.setObjectName("get_M_Y")
        self.get_M_Z = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.get_M_Z.setGeometry(QtCore.QRect(1120, 210, 120, 43))
        self.get_M_Z.setMinimumSize(QtCore.QSize(0, 43))
        self.get_M_Z.setStyleSheet("QLineEdit {\n"
"    background-color: #ecf0f1;  /* 浅灰色背景 */\n"
"    color: #2c3e50;  /* 文字颜色 */\n"
"    border: 2px solid #bdc3c7;  /* 默认边框 */\n"
"    border-radius: 10px;  /* 圆角 */\n"
"    font-size: 18px;  /* 字体大小，增加到18px */\n"
"    padding: 12px 16px;  /* 增大内边距，使文字更居中 */\n"
"    min-height: 15px;  /* 设置最小高度，保证输入框足够大 */ \n"
"    selection-background-color: #3498db;  /* 选中文字背景色 */\n"
"    selection-color: white;  /* 选中文字颜色 */\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid #95a5a6;  /* 悬停时边框颜色 */\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid #3498db;  /* 聚焦时边框变蓝 */\n"
"    background-color: white;  /* 聚焦时背景变白 */\n"
"}\n"
"QLineEdit:disabled {\n"
"    background-color: #bdc3c7;  /* 禁用时背景变灰 */\n"
"    color: #7f8c8d;  /* 禁用时字体颜色变暗 */\n"
"}\n"
"")
        self.get_M_Z.setObjectName("get_M_Z")
        self.get_M_Rx = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.get_M_Rx.setGeometry(QtCore.QRect(1120, 260, 120, 43))
        self.get_M_Rx.setMinimumSize(QtCore.QSize(0, 43))
        self.get_M_Rx.setStyleSheet("QLineEdit {\n"
"    background-color: #ecf0f1;  /* 浅灰色背景 */\n"
"    color: #2c3e50;  /* 文字颜色 */\n"
"    border: 2px solid #bdc3c7;  /* 默认边框 */\n"
"    border-radius: 10px;  /* 圆角 */\n"
"    font-size: 18px;  /* 字体大小，增加到18px */\n"
"    padding: 12px 16px;  /* 增大内边距，使文字更居中 */\n"
"    min-height: 15px;  /* 设置最小高度，保证输入框足够大 */ \n"
"    selection-background-color: #3498db;  /* 选中文字背景色 */\n"
"    selection-color: white;  /* 选中文字颜色 */\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid #95a5a6;  /* 悬停时边框颜色 */\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid #3498db;  /* 聚焦时边框变蓝 */\n"
"    background-color: white;  /* 聚焦时背景变白 */\n"
"}\n"
"QLineEdit:disabled {\n"
"    background-color: #bdc3c7;  /* 禁用时背景变灰 */\n"
"    color: #7f8c8d;  /* 禁用时字体颜色变暗 */\n"
"}\n"
"")
        self.get_M_Rx.setObjectName("get_M_Rx")
        self.get_M_Ry = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.get_M_Ry.setGeometry(QtCore.QRect(1120, 310, 120, 43))
        self.get_M_Ry.setMinimumSize(QtCore.QSize(0, 43))
        self.get_M_Ry.setStyleSheet("QLineEdit {\n"
"    background-color: #ecf0f1;  /* 浅灰色背景 */\n"
"    color: #2c3e50;  /* 文字颜色 */\n"
"    border: 2px solid #bdc3c7;  /* 默认边框 */\n"
"    border-radius: 10px;  /* 圆角 */\n"
"    font-size: 18px;  /* 字体大小，增加到18px */\n"
"    padding: 12px 16px;  /* 增大内边距，使文字更居中 */\n"
"    min-height: 15px;  /* 设置最小高度，保证输入框足够大 */ \n"
"    selection-background-color: #3498db;  /* 选中文字背景色 */\n"
"    selection-color: white;  /* 选中文字颜色 */\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid #95a5a6;  /* 悬停时边框颜色 */\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid #3498db;  /* 聚焦时边框变蓝 */\n"
"    background-color: white;  /* 聚焦时背景变白 */\n"
"}\n"
"QLineEdit:disabled {\n"
"    background-color: #bdc3c7;  /* 禁用时背景变灰 */\n"
"    color: #7f8c8d;  /* 禁用时字体颜色变暗 */\n"
"}\n"
"")
        self.get_M_Ry.setObjectName("get_M_Ry")
        self.get_M_Rz = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.get_M_Rz.setGeometry(QtCore.QRect(1120, 360, 120, 43))
        self.get_M_Rz.setMinimumSize(QtCore.QSize(0, 43))
        self.get_M_Rz.setStyleSheet("QLineEdit {\n"
"    background-color: #ecf0f1;  /* 浅灰色背景 */\n"
"    color: #2c3e50;  /* 文字颜色 */\n"
"    border: 2px solid #bdc3c7;  /* 默认边框 */\n"
"    border-radius: 10px;  /* 圆角 */\n"
"    font-size: 18px;  /* 字体大小，增加到18px */\n"
"    padding: 12px 16px;  /* 增大内边距，使文字更居中 */\n"
"    min-height: 15px;  /* 设置最小高度，保证输入框足够大 */ \n"
"    selection-background-color: #3498db;  /* 选中文字背景色 */\n"
"    selection-color: white;  /* 选中文字颜色 */\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid #95a5a6;  /* 悬停时边框颜色 */\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid #3498db;  /* 聚焦时边框变蓝 */\n"
"    background-color: white;  /* 聚焦时背景变白 */\n"
"}\n"
"QLineEdit:disabled {\n"
"    background-color: #bdc3c7;  /* 禁用时背景变灰 */\n"
"    color: #7f8c8d;  /* 禁用时字体颜色变暗 */\n"
"}\n"
"")
        self.get_M_Rz.setObjectName("get_M_Rz")
        self.Move_J_C_btm = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Move_J_C_btm.setGeometry(QtCore.QRect(1130, 510, 100, 40))
        self.Move_J_C_btm.setMinimumSize(QtCore.QSize(0, 0))
        self.Move_J_C_btm.setMaximumSize(QtCore.QSize(190, 70))
        self.Move_J_C_btm.setStyleSheet("QPushButton {\n"
"    background-color: #A9DFBF;  /* 柔和的浅绿色 */\n"
"    color: black;  /* 文字颜色（黑色，提高可读性） */\n"
"    border-radius: 10px;  /* 圆角 */\n"
"    font-size: 16px;  /* 字体大小 */\n"
"    padding: 8px 16px;  /* 内边距 */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #7DCEA0; /* 悬停时颜色，更亮的绿色 */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #52BE80; /* 按下时颜色，稍深 */\n"
"}\n"
"")
        self.Move_J_C_btm.setObjectName("Move_J_C_btm")
        self.Move_L_C_btm = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Move_L_C_btm.setGeometry(QtCore.QRect(1130, 560, 100, 40))
        self.Move_L_C_btm.setMinimumSize(QtCore.QSize(0, 0))
        self.Move_L_C_btm.setMaximumSize(QtCore.QSize(190, 70))
        self.Move_L_C_btm.setStyleSheet("QPushButton {\n"
"    background-color: #A9DFBF;  /* 柔和的浅绿色 */\n"
"    color: black;  /* 文字颜色（黑色，提高可读性） */\n"
"    border-radius: 10px;  /* 圆角 */\n"
"    font-size: 16px;  /* 字体大小 */\n"
"    padding: 8px 16px;  /* 内边距 */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #7DCEA0; /* 悬停时颜色，更亮的绿色 */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #52BE80; /* 按下时颜色，稍深 */\n"
"}\n"
"")
        self.Move_L_C_btm.setObjectName("Move_L_C_btm")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1413, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Dobot_HMI"))
        self.connect.setText(_translate("MainWindow", "Connect"))
        self.IP_Adress.setText(_translate("MainWindow", "IP Adress"))
        self.Dashboard_Port.setText(_translate("MainWindow", "Dashboard Port"))
        self.Feedback_Port.setText(_translate("MainWindow", "Feedback Port"))
        self.Enable.setText(_translate("MainWindow", "Enable"))
        self.J1.setText(_translate("MainWindow", "J1"))
        self.J2.setText(_translate("MainWindow", "J2"))
        self.J3.setText(_translate("MainWindow", "J3"))
        self.J4.setText(_translate("MainWindow", "J4"))
        self.J5.setText(_translate("MainWindow", "J6"))
        self.J6.setText(_translate("MainWindow", "J5"))
        self.J1P.setText(_translate("MainWindow", "J1+"))
        self.J1N.setText(_translate("MainWindow", "J1-"))
        self.J2P.setText(_translate("MainWindow", "J2+"))
        self.J3P.setText(_translate("MainWindow", "J3+"))
        self.J4P.setText(_translate("MainWindow", "J4+"))
        self.J5P.setText(_translate("MainWindow", "J5+"))
        self.J6P.setText(_translate("MainWindow", "J6+"))
        self.J2N.setText(_translate("MainWindow", "J2-"))
        self.J3N.setText(_translate("MainWindow", "J3-"))
        self.J4N.setText(_translate("MainWindow", "J4-"))
        self.J5N.setText(_translate("MainWindow", "J5-"))
        self.J6N.setText(_translate("MainWindow", "J6-"))
        self.X.setText(_translate("MainWindow", "X"))
        self.Y.setText(_translate("MainWindow", "Y"))
        self.Z.setText(_translate("MainWindow", "Z"))
        self.Rx.setText(_translate("MainWindow", "Rx"))
        self.Ry.setText(_translate("MainWindow", "Ry"))
        self.X_6.setText(_translate("MainWindow", "Rz"))
        self.XP.setText(_translate("MainWindow", "X+"))
        self.YP.setText(_translate("MainWindow", "Y+"))
        self.ZP.setText(_translate("MainWindow", "Z+"))
        self.RxP.setText(_translate("MainWindow", "Rx+"))
        self.RyP.setText(_translate("MainWindow", "Ry+"))
        self.RzP.setText(_translate("MainWindow", "Rz+"))
        self.XN.setText(_translate("MainWindow", "X-"))
        self.YN.setText(_translate("MainWindow", "Y-"))
        self.ZN.setText(_translate("MainWindow", "Z-"))
        self.RxN.setText(_translate("MainWindow", "Rx-"))
        self.RyN.setText(_translate("MainWindow", "Ry-"))
        self.RzN.setText(_translate("MainWindow", "Rz-"))
        self.runScriptBtn.setText(_translate("MainWindow", "Start"))
        self.pauseBtn.setText(_translate("MainWindow", "Pause"))
        self.continueBtn.setText(_translate("MainWindow", "Continue"))
        self.stopBtn.setText(_translate("MainWindow", "Stop"))
        self.Script_txt.setText(_translate("MainWindow", "Script"))
        self.Move_txt.setText(_translate("MainWindow", "Move Function"))
        self.M_J1.setText(_translate("MainWindow", "J1"))
        self.M_J2.setText(_translate("MainWindow", "J2"))
        self.M_J3.setText(_translate("MainWindow", "J3"))
        self.M_J4.setText(_translate("MainWindow", "J4"))
        self.M_J5.setText(_translate("MainWindow", "J5"))
        self.M_J6.setText(_translate("MainWindow", "J6"))
        self.Acc_text.setText(_translate("MainWindow", " Acc. Rate (0-100)"))
        self.Vel_text.setText(_translate("MainWindow", " Vel. Rate (0-100)"))
        self.Move_J_btm.setText(_translate("MainWindow", "MoveJ"))
        self.M_X.setText(_translate("MainWindow", "X"))
        self.M_Y.setText(_translate("MainWindow", "Y"))
        self.M_Z.setText(_translate("MainWindow", "Z"))
        self.M_Rx.setText(_translate("MainWindow", "Rx"))
        self.M_Ry.setText(_translate("MainWindow", "Ry"))
        self.M_Rz.setText(_translate("MainWindow", "Rz"))
        self.Move_J_C_btm.setText(_translate("MainWindow", "MoveJ"))
        self.Move_L_C_btm.setText(_translate("MainWindow", "MoveL"))
